// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NewQuestionForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form id=\"myForm\" hx-post=\"/newquestion\" hx-indicator=\"#indicator\"><div class=\"flex flex-col items-start gap-3\"><div class=\"flex flex-col\"><label for=\"textInput\">Text Input:</label> <input class=\"rounded-sm p-2 border-2 border-blue-500\" type=\"text\" id=\"textInput\" name=\"textInput\" autofocus></div><div class=\"flex items-center gap-1\"><input type=\"checkbox\" id=\"checkboxInput\" name=\"checkboxInput\"> <label for=\"checkboxInput\">I agree to the terms and conditions:</label></div><button class=\"border-2 border-red-500 p-4\" type=\"submit\">Submit</button> <img id=\"indicator\" class=\"htmx-indicator\" src=\"/spinner.gif\"></div></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
