version: '3'

services:
  client:
    build:
      context: ./client-sk
    ports:
      - 5173:5173
    environment:
      - PUBLIC_API_BASE_URL=http://api:3333
      - VITE_VERSION_INFO=docker-compose
  api:
    build:
      context: ./api
    ports:
      - 3333:3333
    env_file:
      - ./api/env.yaml
