services:
  api:
    build:
      context: ../api
    ports:
      - 3333:3333
    env_file:
      - ../api/env.yaml
    environment:
      POSTGRESQL_CONNECTION_STRING_SECRET: postgresql://pgcomposeusr:pgcomposepw@postgres:5432/pgcomposeusr
    depends_on:
      - postgres  

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgcomposeusr
      POSTGRES_PASSWORD: pgcomposepw
    volumes:
      - ../api/test/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      
  beyla:
    image: grafana/beyla:latest
    container_name: beyla
    pid: "service:api"
    privileged: true
    environment:
      BEYLA_TRACE_PRINTER: text
      BEYLA_OPEN_PORT: 3333
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
  
  tempo:
    image: grafana/tempo
    container_name: tempo
    restart: unless-stopped
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 4318:4318
      - 3200:3200
  
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib
    restart: unless-stopped
    volumes:
    - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889
      - 13133:13133 # health_check extension
      - 4319:4318 # OTLP http receiver

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3050:3000
    volumes:
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./dashboard-provider.yaml:/etc/grafana/provisioning/dashboards/dashboard-provider.yaml
      - ./beyla-red-dashboard.json:/dashboard-definitions/local/beyla-red-dashboard.json.json

    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    expose:
      - 9090