global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'cpvt'
    scrape_interval: 15s
    static_configs:
      - targets: ['otel-collector:8889']