name: CI Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:   
  build_api:
    name: Build Go Api
    runs-on: ubuntu-latest
    steps:
        - name: Set current date as env variable
          run: echo "TODAY=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        - uses: actions/checkout@v3
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to ACR
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.ACR_SERVER }}
            username: ${{ secrets.ACR_USER_NAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: ./api
            push: true
            platforms: linux/amd64
            tags: hoodini/cpvt-api:${{ env.TODAY }}.${{ github.run_number }}, hoodini/cpvt-api:latest
  build_web:
    name: Build Svelte Web App
    runs-on: ubuntu-latest
    steps:
        - name: Set current date as env variable
          run: echo "TODAY=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        - uses: actions/checkout@v3
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to ACR
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.ACR_SERVER }}
            username: ${{ secrets.ACR_USER_NAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: ./client
            push: true
            platforms: linux/amd64
            tags: hoodini/cpvt-web:${{ env.TODAY }}.${{ github.run_number }}, hoodini/cpvt-api:latest