name: CI Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:   
  build_api:
    name: Build Go Api
    runs-on: ubuntu-latest
    steps:
        - name: Set short commit as buildtag env variable
          run: echo "BUILDTAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
        - uses: actions/checkout@v3
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to ACR
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.ACR_SERVER }}
            username: ${{ secrets.ACR_USER_NAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: ./api
            push: true
            platforms: linux/amd64
            tags: ${{ secrets.ACR_SERVER }}/cpvt-api:${{ env.BUILDTAG }}, ${{ secrets.ACR_SERVER }}/cpvt-api:latest

  build_web:
    name: Build Svelte Web App
    runs-on: ubuntu-latest
    env: 
      PUBLIC_API_BASE_URL: ${{ vars.PUBLIC_API_BASE_URL }}
    steps:
        - name: Set short commit as buildtag env variable
          run: echo "BUILDTAG=${GITHUB_SHA::7}" >> $GITHUB_ENV
        - uses: actions/checkout@v3
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to ACR
          uses: docker/login-action@v2
          with:
            registry: ${{ secrets.ACR_SERVER }}
            username: ${{ secrets.ACR_USER_NAME }}
            password: ${{ secrets.ACR_PASSWORD }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: ./client-sk
            push: true
            platforms: linux/amd64
            build-args: |
              version_info=${{ env.BUILDTAG }}
            tags: ${{ secrets.ACR_SERVER }}/cpvt-web:${{ env.BUILDTAG }}, ${{ secrets.ACR_SERVER }}/cpvt-web:latest