name: CI Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:   
  test:
    name: Test Go Api
    runs-on: ubuntu-latest
    container: 
      image: golang:1.20-alpine
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: api
        run: go get .
      - name: Test
        working-directory: api
        run: go test -v ./...
  build:
    name: Build Go Api
    runs-on: ubuntu-latest
    needs: ['test']
    steps:
        - name: Set current date as env variable
          run: echo "TODAY=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
        - uses: actions/checkout@v3
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USER }}
            password: ${{ secrets.DOCKER_HUB_PW }}
        -
          name: Build and push
          uses: docker/build-push-action@v3
          with:
            context: ./api
            push: true
            platforms: linux/amd64
            tags: hoodini/cpvotingtool:${{ env.TODAY }}.${{ github.run_number }}, hoodini/cpvotingtool:latest